/* Generated by Yosys 0.36 (git sha1 8f07a0d8404, clang 14.0.3 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "ex416.sv:1.1-6.10" *)
module mux2_8(d0, d1, s, y);
  (* src = "ex416.sv:1.34-1.36" *)
  input [7:0] d0;
  wire [7:0] d0;
  (* src = "ex416.sv:1.38-1.40" *)
  input [7:0] d1;
  wire [7:0] d1;
  (* src = "ex416.sv:2.28-2.29" *)
  input s;
  wire s;
  (* src = "ex416.sv:3.34-3.35" *)
  output [7:0] y;
  wire [7:0] y;
  (* module_not_derived = 32'd1 *)
  (* src = "ex416.sv:4.10-4.45" *)
  mux2 lsbmux (
    d0[3:0],
    d1[3:0],
    s,
    y[3:0]
  );
  (* module_not_derived = 32'd1 *)
  (* src = "ex416.sv:5.10-5.45" *)
  mux2 msbmux (
    d0[7:4],
    d1[7:4],
    s,
    y[7:4]
  );
endmodule
